{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "63f5cc91-0d4e-4919-b180-99915abe035f",
   "metadata": {
    "tags": []
   },
   "source": [
    "## Preprocess"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "33fc4b58-d955-4453-8053-41e4183a186c",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:05.204286Z",
     "iopub.status.busy": "2024-09-13T08:36:05.203172Z",
     "iopub.status.idle": "2024-09-13T08:36:05.245909Z",
     "shell.execute_reply": "2024-09-13T08:36:05.244986Z",
     "shell.execute_reply.started": "2024-09-13T08:36:05.204237Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "fc71c9a8-1042-456d-b0f6-934d9273bfde",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:05.712802Z",
     "iopub.status.busy": "2024-09-13T08:36:05.711777Z",
     "iopub.status.idle": "2024-09-13T08:36:05.962977Z",
     "shell.execute_reply": "2024-09-13T08:36:05.961993Z",
     "shell.execute_reply.started": "2024-09-13T08:36:05.712761Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "# Загрузка исходного XLSX файла\n",
    "input_file = '/home/jupyter/datasphere/project/v2_ragas_npa_dataset_firstPart.xlsx'  # Укажите путь к вашему файлу\n",
    "df = pd.read_excel(input_file)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "53f47266-277e-4fab-beaf-8630aba9ce26",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:05.965383Z",
     "iopub.status.busy": "2024-09-13T08:36:05.964479Z",
     "iopub.status.idle": "2024-09-13T08:36:06.007522Z",
     "shell.execute_reply": "2024-09-13T08:36:06.006562Z",
     "shell.execute_reply.started": "2024-09-13T08:36:05.965344Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0      Каков объем экспорта услуг категории \"Поездки\"...\n",
       "1      Каковы были основные мероприятия, реализуемые ...\n",
       "2      Каков размер финансирования из федерального бю...\n",
       "3      Какой комплексный центр социального обслуживан...\n",
       "4      Какое значение имеет экологическое образование...\n",
       "                             ...                        \n",
       "495                Что входит в расходы госорганов Югры?\n",
       "496    Как изменился объем переработки газа в 2009 году?\n",
       "497    Что дает программа \"Развитие материально-техни...\n",
       "498            Какую долю занимают средства Нефтеюганск?\n",
       "499    Субвенции ХМАО-Югры: как распределяются и что ...\n",
       "Name: question, Length: 500, dtype: object"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['question']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "4e9f0277-2308-404e-8984-0aa44385958b",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:06.009702Z",
     "iopub.status.busy": "2024-09-13T08:36:06.008578Z",
     "iopub.status.idle": "2024-09-13T08:36:06.042716Z",
     "shell.execute_reply": "2024-09-13T08:36:06.041853Z",
     "shell.execute_reply.started": "2024-09-13T08:36:06.009663Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "pattern = r\"^\\['(.*)'\\]$\"\n",
    "\n",
    "df['contexts'] = df['contexts'].str.replace(pattern, r'\\1', regex=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "106d961c-e5b0-432b-bcda-bb92fb595473",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:06.045055Z",
     "iopub.status.busy": "2024-09-13T08:36:06.044456Z",
     "iopub.status.idle": "2024-09-13T08:36:06.082577Z",
     "shell.execute_reply": "2024-09-13T08:36:06.081662Z",
     "shell.execute_reply.started": "2024-09-13T08:36:06.045020Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0    Увеличение объема экспорта услуг категории \"По...\n",
       "1    и | |развития | | |Ханты-Мансийского |исполнит...\n",
       "2    не относящиеся к районам Крайнего Севера и при...\n",
       "3    |2.2. |Центр социальной |240 к/мест |7580,0 |2...\n",
       "4    (полного)общего образования и начального профе...\n",
       "Name: contexts, dtype: object"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['contexts'].head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "ac100ac2-e526-444f-800b-0fd9b1f302f1",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:06.084369Z",
     "iopub.status.busy": "2024-09-13T08:36:06.083649Z",
     "iopub.status.idle": "2024-09-13T08:36:06.166170Z",
     "shell.execute_reply": "2024-09-13T08:36:06.165017Z",
     "shell.execute_reply.started": "2024-09-13T08:36:06.084332Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "answer = 'Оценка релевантности: набор фрагментов документов релевантен, так как в них содержатся ключевые слова и семантические значения, связанные с вопросом пользователя о реформах, связанных с ветеранами труда.\\n\\n**Ключевые слова:** ветераны труда, ветераны Великой Отечественной войны, ветераны боевых действий, труженики тыла, меры социальной поддержки, присвоение звания «ветеран труда», льготы, субсидии, законы «О ветеранах», «О мерах социальной поддержки отдельных категорий граждан».\\n\\nВ представленных фрагментах документов описывается законодательство и меры поддержки ветеранов труда и других категорий граждан, а также изменения и дополнения к этим законам. Это указывает на наличие информации о возможных реформах в этой области. Однако конкретные сведения о введении новых реформ или изменениях в законодательстве требуют более детального анализа и выделения конкретных цитат из фрагментов.'"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c6c458e8-1200-463f-ad67-9e68829ba7fc",
   "metadata": {},
   "source": [
    "## IMPORTS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "078361f2-9fc6-4aa9-8896-e634c6e09081",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:06.168125Z",
     "iopub.status.busy": "2024-09-13T08:36:06.167293Z",
     "iopub.status.idle": "2024-09-13T08:36:09.144691Z",
     "shell.execute_reply": "2024-09-13T08:36:09.143752Z",
     "shell.execute_reply.started": "2024-09-13T08:36:06.168087Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: ragas in /home/jupyter/.local/lib/python3.10/site-packages (0.1.18)\n",
      "Requirement already satisfied: numpy in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (1.26.4)\n",
      "Requirement already satisfied: datasets in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (2.21.0)\n",
      "Requirement already satisfied: tiktoken in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (0.7.0)\n",
      "Requirement already satisfied: langchain in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (0.2.16)\n",
      "Requirement already satisfied: langchain-core in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (0.2.39)\n",
      "Requirement already satisfied: langchain-community in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (0.2.16)\n",
      "Requirement already satisfied: langchain-openai in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (0.1.24)\n",
      "Requirement already satisfied: openai>1 in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (1.44.1)\n",
      "Requirement already satisfied: pysbd>=0.3.4 in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (0.3.4)\n",
      "Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/dist-packages (from ragas) (1.5.6)\n",
      "Requirement already satisfied: appdirs in /usr/local/lib/python3.10/dist-packages (from ragas) (1.4.4)\n",
      "Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai>1->ragas) (3.7.1)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai>1->ragas) (1.7.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in /home/jupyter/.local/lib/python3.10/site-packages (from openai>1->ragas) (0.27.2)\n",
      "Requirement already satisfied: jiter<1,>=0.4.0 in /home/jupyter/.local/lib/python3.10/site-packages (from openai>1->ragas) (0.5.0)\n",
      "Requirement already satisfied: pydantic<3,>=1.9.0 in /home/jupyter/.local/lib/python3.10/site-packages (from openai>1->ragas) (2.6.0)\n",
      "Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai>1->ragas) (1.3.0)\n",
      "Requirement already satisfied: tqdm>4 in /home/jupyter/.local/lib/python3.10/site-packages (from openai>1->ragas) (4.66.5)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.11 in /home/jupyter/.local/lib/python3.10/site-packages (from openai>1->ragas) (4.12.2)\n",
      "Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets->ragas) (3.12.2)\n",
      "Requirement already satisfied: pyarrow>=15.0.0 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (17.0.0)\n",
      "Requirement already satisfied: dill<0.3.9,>=0.3.0 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (0.3.8)\n",
      "Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets->ragas) (1.5.3)\n",
      "Requirement already satisfied: requests>=2.32.2 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (2.32.3)\n",
      "Requirement already satisfied: xxhash in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (3.5.0)\n",
      "Requirement already satisfied: multiprocess in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (0.70.16)\n",
      "Requirement already satisfied: fsspec<=2024.6.1,>=2023.1.0 in /home/jupyter/.local/lib/python3.10/site-packages (from fsspec[http]<=2024.6.1,>=2023.1.0->datasets->ragas) (2024.6.1)\n",
      "Requirement already satisfied: aiohttp in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (3.10.5)\n",
      "Requirement already satisfied: huggingface-hub>=0.21.2 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (0.24.7)\n",
      "Requirement already satisfied: packaging in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (23.2)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets->ragas) (6.0.1)\n",
      "Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.10/dist-packages (from langchain->ragas) (2.0.19)\n",
      "Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from langchain->ragas) (4.0.2)\n",
      "Requirement already satisfied: langchain-text-splitters<0.3.0,>=0.2.0 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain->ragas) (0.2.4)\n",
      "Requirement already satisfied: langsmith<0.2.0,>=0.1.17 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain->ragas) (0.1.116)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<9.0.0,>=8.1.0 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain->ragas) (8.5.0)\n",
      "Requirement already satisfied: jsonpatch<2.0,>=1.33 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain-core->ragas) (1.33)\n",
      "Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain-community->ragas) (0.5.14)\n",
      "Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.10/dist-packages (from tiktoken->ragas) (2022.10.31)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/jupyter/.local/lib/python3.10/site-packages (from aiohttp->datasets->ragas) (2.4.0)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->ragas) (1.3.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->ragas) (23.1.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->ragas) (1.4.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->ragas) (6.0.4)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->ragas) (1.9.2)\n",
      "Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai>1->ragas) (3.4)\n",
      "Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai>1->ragas) (1.1.2)\n",
      "Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /home/jupyter/.local/lib/python3.10/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community->ragas) (3.22.0)\n",
      "Requirement already satisfied: typing-inspect<1,>=0.4.0 in /home/jupyter/.local/lib/python3.10/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community->ragas) (0.9.0)\n",
      "Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai>1->ragas) (2023.7.22)\n",
      "Requirement already satisfied: httpcore==1.* in /home/jupyter/.local/lib/python3.10/site-packages (from httpx<1,>=0.23.0->openai>1->ragas) (1.0.5)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in /home/jupyter/.local/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai>1->ragas) (0.14.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in /home/jupyter/.local/lib/python3.10/site-packages (from jsonpatch<2.0,>=1.33->langchain-core->ragas) (3.0.0)\n",
      "Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /home/jupyter/.local/lib/python3.10/site-packages (from langsmith<0.2.0,>=0.1.17->langchain->ragas) (3.10.7)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in /home/jupyter/.local/lib/python3.10/site-packages (from pydantic<3,>=1.9.0->openai>1->ragas) (0.7.0)\n",
      "Requirement already satisfied: pydantic-core==2.16.1 in /home/jupyter/.local/lib/python3.10/site-packages (from pydantic<3,>=1.9.0->openai>1->ragas) (2.16.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets->ragas) (2.0.12)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jupyter/.local/lib/python3.10/site-packages (from requests>=2.32.2->datasets->ragas) (2.2.2)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<3,>=1.4->langchain->ragas) (2.0.2)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->ragas) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->ragas) (2022.7.1)\n",
      "Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas->datasets->ragas) (1.16.0)\n",
      "Requirement already satisfied: mypy-extensions>=0.3.0 in /home/jupyter/.local/lib/python3.10/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community->ragas) (1.0.0)\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.2\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "%pip install ragas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "596fa0cf-7950-4a0a-b4dd-1d1a20be8991",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:09.146730Z",
     "iopub.status.busy": "2024-09-13T08:36:09.145880Z",
     "iopub.status.idle": "2024-09-13T08:36:11.821381Z",
     "shell.execute_reply": "2024-09-13T08:36:11.820590Z",
     "shell.execute_reply.started": "2024-09-13T08:36:09.146689Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "from ragas.metrics import faithfulness, answer_relevancy, context_recall, context_precision\n",
    "from ragas import evaluate "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "74bbc149-91ee-4e55-b99a-e4487e2bb447",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:11.824358Z",
     "iopub.status.busy": "2024-09-13T08:36:11.823457Z",
     "iopub.status.idle": "2024-09-13T08:36:11.843351Z",
     "shell.execute_reply": "2024-09-13T08:36:11.842540Z",
     "shell.execute_reply.started": "2024-09-13T08:36:11.824328Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "from datasets import Dataset\n",
    "from ragas.metrics import faithfulness, answer_correctness"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "b04d8875-3d6c-41b4-8187-89d9deffadd8",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:11.845480Z",
     "iopub.status.busy": "2024-09-13T08:36:11.844310Z",
     "iopub.status.idle": "2024-09-13T08:36:11.875842Z",
     "shell.execute_reply": "2024-09-13T08:36:11.875014Z",
     "shell.execute_reply.started": "2024-09-13T08:36:11.845447Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "from ragas.llms import LangchainLLMWrapper"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "4d86f1cc-016c-42d7-a209-bde9079b244e",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:11.877395Z",
     "iopub.status.busy": "2024-09-13T08:36:11.876803Z",
     "iopub.status.idle": "2024-09-13T08:36:14.567850Z",
     "shell.execute_reply": "2024-09-13T08:36:14.566770Z",
     "shell.execute_reply.started": "2024-09-13T08:36:11.877357Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: yandexcloud in /home/jupyter/.local/lib/python3.10/site-packages (0.316.0)\n",
      "Requirement already satisfied: cryptography<43,>=41.0.7 in /home/jupyter/.local/lib/python3.10/site-packages (from yandexcloud) (42.0.8)\n",
      "Requirement already satisfied: grpcio<2,>=1.64.0 in /home/jupyter/.local/lib/python3.10/site-packages (from yandexcloud) (1.66.1)\n",
      "Requirement already satisfied: protobuf<5,>=4.25.3 in /home/jupyter/.local/lib/python3.10/site-packages (from yandexcloud) (4.25.4)\n",
      "Requirement already satisfied: googleapis-common-protos<2,>=1.63.0 in /home/jupyter/.local/lib/python3.10/site-packages (from yandexcloud) (1.65.0)\n",
      "Requirement already satisfied: pyjwt<3,>=2.8.0 in /home/jupyter/.local/lib/python3.10/site-packages (from yandexcloud) (2.9.0)\n",
      "Requirement already satisfied: requests<3,>=2.32.3 in /home/jupyter/.local/lib/python3.10/site-packages (from yandexcloud) (2.32.3)\n",
      "Requirement already satisfied: six<2,>=1.16.0 in /usr/lib/python3/dist-packages (from yandexcloud) (1.16.0)\n",
      "Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography<43,>=41.0.7->yandexcloud) (1.15.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.32.3->yandexcloud) (2.0.12)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.32.3->yandexcloud) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jupyter/.local/lib/python3.10/site-packages (from requests<3,>=2.32.3->yandexcloud) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.32.3->yandexcloud) (2023.7.22)\n",
      "Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12->cryptography<43,>=41.0.7->yandexcloud) (2.21)\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.2\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "%pip install yandexcloud"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "f997f585-fd54-4c5f-bb93-c4c1b228b2eb",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:14.569891Z",
     "iopub.status.busy": "2024-09-13T08:36:14.569189Z",
     "iopub.status.idle": "2024-09-13T08:36:14.601700Z",
     "shell.execute_reply": "2024-09-13T08:36:14.600757Z",
     "shell.execute_reply.started": "2024-09-13T08:36:14.569860Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "from langchain_core.language_models import BaseLanguageModel\n",
    "from langchain_core.embeddings import Embeddings\n",
    "from langchain_community.chat_models import ChatYandexGPT\n",
    "from langchain_community.llms import YandexGPT"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "45da15de-50f3-4060-9804-6a5e45dfa07c",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:41:30.400534Z",
     "iopub.status.busy": "2024-09-13T08:41:30.399316Z",
     "iopub.status.idle": "2024-09-13T08:41:30.432640Z",
     "shell.execute_reply": "2024-09-13T08:41:30.431815Z",
     "shell.execute_reply.started": "2024-09-13T08:41:30.400484Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "llm = YandexGPT(iam_token='', folder_id='b1g5pkij4170jm1a1un6', temperature=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "75ed22b0-40ae-4a20-8c84-270412d23095",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:14.640909Z",
     "iopub.status.busy": "2024-09-13T08:36:14.640098Z",
     "iopub.status.idle": "2024-09-13T08:36:35.390239Z",
     "shell.execute_reply": "2024-09-13T08:36:35.389276Z",
     "shell.execute_reply.started": "2024-09-13T08:36:14.640867Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: langchain_community in /home/jupyter/.local/lib/python3.10/site-packages (0.2.16)\n",
      "Requirement already satisfied: tiktoken in /home/jupyter/.local/lib/python3.10/site-packages (0.7.0)\n",
      "Requirement already satisfied: langchain-openai in /home/jupyter/.local/lib/python3.10/site-packages (0.1.24)\n",
      "Requirement already satisfied: langchainhub in /home/jupyter/.local/lib/python3.10/site-packages (0.1.21)\n",
      "Requirement already satisfied: langchain in /home/jupyter/.local/lib/python3.10/site-packages (0.2.16)\n",
      "Requirement already satisfied: langgraph in /home/jupyter/.local/lib/python3.10/site-packages (0.2.19)\n",
      "Requirement already satisfied: langchain_huggingface in /home/jupyter/.local/lib/python3.10/site-packages (0.0.3)\n",
      "Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (6.0.1)\n",
      "Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (2.0.19)\n",
      "Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain_community) (3.10.5)\n",
      "Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain_community) (0.5.14)\n",
      "Requirement already satisfied: langchain-core<0.3.0,>=0.2.38 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain_community) (0.2.39)\n",
      "Requirement already satisfied: langsmith<0.2.0,>=0.1.0 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain_community) (0.1.116)\n",
      "Requirement already satisfied: numpy<2,>=1 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain_community) (1.26.4)\n",
      "Requirement already satisfied: requests<3,>=2 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain_community) (2.32.3)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<9.0.0,>=8.1.0 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain_community) (8.5.0)\n",
      "Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.10/dist-packages (from tiktoken) (2022.10.31)\n",
      "Requirement already satisfied: openai<2.0.0,>=1.40.0 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain-openai) (1.44.1)\n",
      "Requirement already satisfied: packaging<25,>=23.2 in /home/jupyter/.local/lib/python3.10/site-packages (from langchainhub) (23.2)\n",
      "Requirement already satisfied: types-requests<3.0.0.0,>=2.31.0.2 in /home/jupyter/.local/lib/python3.10/site-packages (from langchainhub) (2.32.0.20240907)\n",
      "Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (4.0.2)\n",
      "Requirement already satisfied: langchain-text-splitters<0.3.0,>=0.2.0 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain) (0.2.4)\n",
      "Requirement already satisfied: pydantic<3,>=1 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain) (2.6.0)\n",
      "Requirement already satisfied: langgraph-checkpoint<2.0.0,>=1.0.2 in /home/jupyter/.local/lib/python3.10/site-packages (from langgraph) (1.0.9)\n",
      "Requirement already satisfied: huggingface-hub>=0.23.0 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain_huggingface) (0.24.7)\n",
      "Requirement already satisfied: sentence-transformers>=2.6.0 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain_huggingface) (3.1.0)\n",
      "Requirement already satisfied: tokenizers>=0.19.1 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain_huggingface) (0.19.1)\n",
      "Requirement already satisfied: transformers>=4.39.0 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain_huggingface) (4.44.2)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/jupyter/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.4.0)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.3.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (23.1.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.0.4)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.9.2)\n",
      "Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /home/jupyter/.local/lib/python3.10/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain_community) (3.22.0)\n",
      "Requirement already satisfied: typing-inspect<1,>=0.4.0 in /home/jupyter/.local/lib/python3.10/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain_community) (0.9.0)\n",
      "Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.23.0->langchain_huggingface) (3.12.2)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in /home/jupyter/.local/lib/python3.10/site-packages (from huggingface-hub>=0.23.0->langchain_huggingface) (2024.6.1)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in /home/jupyter/.local/lib/python3.10/site-packages (from huggingface-hub>=0.23.0->langchain_huggingface) (4.66.5)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/jupyter/.local/lib/python3.10/site-packages (from huggingface-hub>=0.23.0->langchain_huggingface) (4.12.2)\n",
      "Requirement already satisfied: jsonpatch<2.0,>=1.33 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain-core<0.3.0,>=0.2.38->langchain_community) (1.33)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in /home/jupyter/.local/lib/python3.10/site-packages (from langsmith<0.2.0,>=0.1.0->langchain_community) (0.27.2)\n",
      "Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /home/jupyter/.local/lib/python3.10/site-packages (from langsmith<0.2.0,>=0.1.0->langchain_community) (3.10.7)\n",
      "Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai<2.0.0,>=1.40.0->langchain-openai) (3.7.1)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai<2.0.0,>=1.40.0->langchain-openai) (1.7.0)\n",
      "Requirement already satisfied: jiter<1,>=0.4.0 in /home/jupyter/.local/lib/python3.10/site-packages (from openai<2.0.0,>=1.40.0->langchain-openai) (0.5.0)\n",
      "Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai<2.0.0,>=1.40.0->langchain-openai) (1.3.0)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in /home/jupyter/.local/lib/python3.10/site-packages (from pydantic<3,>=1->langchain) (0.7.0)\n",
      "Requirement already satisfied: pydantic-core==2.16.1 in /home/jupyter/.local/lib/python3.10/site-packages (from pydantic<3,>=1->langchain) (2.16.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain_community) (2.0.12)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain_community) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jupyter/.local/lib/python3.10/site-packages (from requests<3,>=2->langchain_community) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain_community) (2023.7.22)\n",
      "Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=2.6.0->langchain_huggingface) (2.0.1+cu118)\n",
      "Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=2.6.0->langchain_huggingface) (1.2.2)\n",
      "Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=2.6.0->langchain_huggingface) (1.10.1)\n",
      "Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=2.6.0->langchain_huggingface) (9.4.0)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<3,>=1.4->langchain_community) (2.0.2)\n",
      "Requirement already satisfied: safetensors>=0.4.1 in /home/jupyter/.local/lib/python3.10/site-packages (from transformers>=4.39.0->langchain_huggingface) (0.4.5)\n",
      "Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai<2.0.0,>=1.40.0->langchain-openai) (1.1.2)\n",
      "Requirement already satisfied: httpcore==1.* in /home/jupyter/.local/lib/python3.10/site-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.0->langchain_community) (1.0.5)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in /home/jupyter/.local/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.0->langchain_community) (0.14.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in /home/jupyter/.local/lib/python3.10/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.3.0,>=0.2.38->langchain_community) (3.0.0)\n",
      "Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (1.11.1)\n",
      "Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (3.1)\n",
      "Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (3.1.2)\n",
      "Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (2.0.0)\n",
      "Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (3.25.2)\n",
      "Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (16.0.6)\n",
      "Requirement already satisfied: mypy-extensions>=0.3.0 in /home/jupyter/.local/lib/python3.10/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain_community) (1.0.0)\n",
      "Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers>=2.6.0->langchain_huggingface) (1.3.1)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers>=2.6.0->langchain_huggingface) (3.2.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (2.1.3)\n",
      "Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (1.3.0)\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.2\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: pymilvus in /home/jupyter/.local/lib/python3.10/site-packages (2.4.6)\n",
      "Requirement already satisfied: sentence-transformers in /home/jupyter/.local/lib/python3.10/site-packages (3.1.0)\n",
      "Requirement already satisfied: fsspec in /home/jupyter/.local/lib/python3.10/site-packages (2024.6.1)\n",
      "Collecting fsspec\n",
      "  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)\n",
      "Requirement already satisfied: s3fs in /home/jupyter/.local/lib/python3.10/site-packages (2024.9.0)\n",
      "Requirement already satisfied: yandexcloud in /home/jupyter/.local/lib/python3.10/site-packages (0.316.0)\n",
      "Requirement already satisfied: transformers in /home/jupyter/.local/lib/python3.10/site-packages (4.44.2)\n",
      "Requirement already satisfied: pip in /kernel/lib/python3.10/site-packages (23.0.1)\n",
      "Collecting pip\n",
      "  Downloading pip-24.2-py3-none-any.whl.metadata (3.6 kB)\n",
      "\u001b[31mERROR: Could not find a version that satisfies the requirement install (from versions: none)\u001b[0m\u001b[31m\n",
      "\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.2\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n",
      "\u001b[31mERROR: No matching distribution found for install\u001b[0m\u001b[31m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: huggingface-hub in /home/jupyter/.local/lib/python3.10/site-packages (0.24.7)\n",
      "Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (3.12.2)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in /home/jupyter/.local/lib/python3.10/site-packages (from huggingface-hub) (2024.6.1)\n",
      "Requirement already satisfied: packaging>=20.9 in /home/jupyter/.local/lib/python3.10/site-packages (from huggingface-hub) (23.2)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (6.0.1)\n",
      "Requirement already satisfied: requests in /home/jupyter/.local/lib/python3.10/site-packages (from huggingface-hub) (2.32.3)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in /home/jupyter/.local/lib/python3.10/site-packages (from huggingface-hub) (4.66.5)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/jupyter/.local/lib/python3.10/site-packages (from huggingface-hub) (4.12.2)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub) (2.0.12)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jupyter/.local/lib/python3.10/site-packages (from requests->huggingface-hub) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub) (2023.7.22)\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.2\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.26.4 which is incompatible.\n",
      "pandas-gbq 0.17.9 requires pyarrow<10.0dev,>=3.0.0, but you have pyarrow 17.0.0 which is incompatible.\n",
      "spacy 3.5.4 requires pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4, but you have pydantic 2.6.0 which is incompatible.\n",
      "tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.26.4 which is incompatible.\n",
      "thinc 8.1.10 requires pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4, but you have pydantic 2.6.0 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.2\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: pydantic==2.6.0 in /home/jupyter/.local/lib/python3.10/site-packages (2.6.0)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in /home/jupyter/.local/lib/python3.10/site-packages (from pydantic==2.6.0) (0.7.0)\n",
      "Requirement already satisfied: pydantic-core==2.16.1 in /home/jupyter/.local/lib/python3.10/site-packages (from pydantic==2.6.0) (2.16.1)\n",
      "Requirement already satisfied: typing-extensions>=4.6.1 in /home/jupyter/.local/lib/python3.10/site-packages (from pydantic==2.6.0) (4.12.2)\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.2\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: ragas in /home/jupyter/.local/lib/python3.10/site-packages (0.1.18)\n",
      "Requirement already satisfied: langchain_openai in /home/jupyter/.local/lib/python3.10/site-packages (0.1.24)\n",
      "Requirement already satisfied: python-dotenv in /home/jupyter/.local/lib/python3.10/site-packages (1.0.1)\n",
      "Requirement already satisfied: numpy in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (1.26.4)\n",
      "Requirement already satisfied: datasets in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (2.21.0)\n",
      "Requirement already satisfied: tiktoken in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (0.7.0)\n",
      "Requirement already satisfied: langchain in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (0.2.16)\n",
      "Requirement already satisfied: langchain-core in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (0.2.39)\n",
      "Requirement already satisfied: langchain-community in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (0.2.16)\n",
      "Requirement already satisfied: openai>1 in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (1.44.1)\n",
      "Requirement already satisfied: pysbd>=0.3.4 in /home/jupyter/.local/lib/python3.10/site-packages (from ragas) (0.3.4)\n",
      "Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/dist-packages (from ragas) (1.5.6)\n",
      "Requirement already satisfied: appdirs in /usr/local/lib/python3.10/dist-packages (from ragas) (1.4.4)\n",
      "Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.10/dist-packages (from langchain-core->ragas) (6.0.1)\n",
      "Requirement already satisfied: jsonpatch<2.0,>=1.33 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain-core->ragas) (1.33)\n",
      "Requirement already satisfied: langsmith<0.2.0,>=0.1.112 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain-core->ragas) (0.1.116)\n",
      "Requirement already satisfied: packaging<25,>=23.2 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain-core->ragas) (23.2)\n",
      "Requirement already satisfied: pydantic<3,>=1 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain-core->ragas) (2.6.0)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<9.0.0,>=8.1.0 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain-core->ragas) (8.5.0)\n",
      "Requirement already satisfied: typing-extensions>=4.7 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain-core->ragas) (4.12.2)\n",
      "Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai>1->ragas) (3.7.1)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai>1->ragas) (1.7.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in /home/jupyter/.local/lib/python3.10/site-packages (from openai>1->ragas) (0.27.2)\n",
      "Requirement already satisfied: jiter<1,>=0.4.0 in /home/jupyter/.local/lib/python3.10/site-packages (from openai>1->ragas) (0.5.0)\n",
      "Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai>1->ragas) (1.3.0)\n",
      "Requirement already satisfied: tqdm>4 in /home/jupyter/.local/lib/python3.10/site-packages (from openai>1->ragas) (4.66.5)\n",
      "Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.10/dist-packages (from tiktoken->ragas) (2022.10.31)\n",
      "Requirement already satisfied: requests>=2.26.0 in /home/jupyter/.local/lib/python3.10/site-packages (from tiktoken->ragas) (2.32.3)\n",
      "Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets->ragas) (3.12.2)\n",
      "Requirement already satisfied: pyarrow>=15.0.0 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (17.0.0)\n",
      "Requirement already satisfied: dill<0.3.9,>=0.3.0 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (0.3.8)\n",
      "Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets->ragas) (1.5.3)\n",
      "Requirement already satisfied: xxhash in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (3.5.0)\n",
      "Requirement already satisfied: multiprocess in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (0.70.16)\n",
      "Requirement already satisfied: fsspec<=2024.6.1,>=2023.1.0 in /home/jupyter/.local/lib/python3.10/site-packages (from fsspec[http]<=2024.6.1,>=2023.1.0->datasets->ragas) (2024.6.1)\n",
      "Requirement already satisfied: aiohttp in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (3.10.5)\n",
      "Requirement already satisfied: huggingface-hub>=0.21.2 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets->ragas) (0.24.7)\n",
      "Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.10/dist-packages (from langchain->ragas) (2.0.19)\n",
      "Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from langchain->ragas) (4.0.2)\n",
      "Requirement already satisfied: langchain-text-splitters<0.3.0,>=0.2.0 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain->ragas) (0.2.4)\n",
      "Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /home/jupyter/.local/lib/python3.10/site-packages (from langchain-community->ragas) (0.5.14)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/jupyter/.local/lib/python3.10/site-packages (from aiohttp->datasets->ragas) (2.4.0)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->ragas) (1.3.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->ragas) (23.1.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->ragas) (1.4.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->ragas) (6.0.4)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->ragas) (1.9.2)\n",
      "Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai>1->ragas) (3.4)\n",
      "Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai>1->ragas) (1.1.2)\n",
      "Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /home/jupyter/.local/lib/python3.10/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community->ragas) (3.22.0)\n",
      "Requirement already satisfied: typing-inspect<1,>=0.4.0 in /home/jupyter/.local/lib/python3.10/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community->ragas) (0.9.0)\n",
      "Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai>1->ragas) (2023.7.22)\n",
      "Requirement already satisfied: httpcore==1.* in /home/jupyter/.local/lib/python3.10/site-packages (from httpx<1,>=0.23.0->openai>1->ragas) (1.0.5)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in /home/jupyter/.local/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai>1->ragas) (0.14.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in /home/jupyter/.local/lib/python3.10/site-packages (from jsonpatch<2.0,>=1.33->langchain-core->ragas) (3.0.0)\n",
      "Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /home/jupyter/.local/lib/python3.10/site-packages (from langsmith<0.2.0,>=0.1.112->langchain-core->ragas) (3.10.7)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in /home/jupyter/.local/lib/python3.10/site-packages (from pydantic<3,>=1->langchain-core->ragas) (0.7.0)\n",
      "Requirement already satisfied: pydantic-core==2.16.1 in /home/jupyter/.local/lib/python3.10/site-packages (from pydantic<3,>=1->langchain-core->ragas) (2.16.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26.0->tiktoken->ragas) (2.0.12)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jupyter/.local/lib/python3.10/site-packages (from requests>=2.26.0->tiktoken->ragas) (2.2.2)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<3,>=1.4->langchain->ragas) (2.0.2)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->ragas) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->ragas) (2022.7.1)\n",
      "Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas->datasets->ragas) (1.16.0)\n",
      "Requirement already satisfied: mypy-extensions>=0.3.0 in /home/jupyter/.local/lib/python3.10/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community->ragas) (1.0.0)\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.2\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "%pip install -U langchain_community tiktoken langchain-openai langchainhub langchain langgraph langchain_huggingface\n",
    "%pip install -U pymilvus sentence-transformers fsspec s3fs yandexcloud transformers pip install langchain-experimental\n",
    "%pip install --upgrade huggingface-hub\n",
    "%pip install -qU  langchain_milvus\n",
    "%pip install pydantic==2.6.0\n",
    "%pip install ragas langchain_openai python-dotenv"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cac4ed68-c5b7-4b43-906b-8cd037f8fd7b",
   "metadata": {},
   "source": [
    "## RAGAS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "ad972125-4339-479a-ab11-89ad2e406f7e",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:35.392831Z",
     "iopub.status.busy": "2024-09-13T08:36:35.391674Z",
     "iopub.status.idle": "2024-09-13T08:36:43.816899Z",
     "shell.execute_reply": "2024-09-13T08:36:43.815922Z",
     "shell.execute_reply.started": "2024-09-13T08:36:35.392788Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "USER_AGENT environment variable not set, consider setting it to identify your requests.\n",
      "/home/jupyter/.local/lib/python3.10/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.\n",
      "  warnings.warn(\n",
      "2024-09-13 08:36:38.835207: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
      "2024-09-13 08:36:38.888678: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-09-13 08:36:39.909475: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n"
     ]
    }
   ],
   "source": [
    "from langchain.text_splitter import RecursiveCharacterTextSplitter\n",
    "from langchain_community.document_loaders import WebBaseLoader\n",
    "from langchain_milvus import Milvus\n",
    "from langchain_huggingface import HuggingFaceEmbeddings\n",
    "from transformers import AutoModel\n",
    "\n",
    "model = AutoModel.from_pretrained(\"deepvk/USER-bge-m3\", trust_remote_code=True) \n",
    "\n",
    "model_name = \"deepvk/USER-bge-m3\"\n",
    "model_kwargs = {'device': 'cpu'}\n",
    "embeddings = HuggingFaceEmbeddings(\n",
    "    model_name=model_name,\n",
    "    model_kwargs=model_kwargs,\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "7befadf5-e17c-4f97-8986-b8b31d4b0042",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:43.818788Z",
     "iopub.status.busy": "2024-09-13T08:36:43.817888Z",
     "iopub.status.idle": "2024-09-13T08:36:43.838009Z",
     "shell.execute_reply": "2024-09-13T08:36:43.837182Z",
     "shell.execute_reply.started": "2024-09-13T08:36:43.818745Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "langchain_llm = LangchainLLMWrapper(langchain_llm=llm)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "8865873f-0f3b-4e93-a366-cf9d0dd470c4",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:43.840342Z",
     "iopub.status.busy": "2024-09-13T08:36:43.839179Z",
     "iopub.status.idle": "2024-09-13T08:36:43.881366Z",
     "shell.execute_reply": "2024-09-13T08:36:43.880454Z",
     "shell.execute_reply.started": "2024-09-13T08:36:43.840309Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'чем обновлять школы округа?'"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import re\n",
    "import string\n",
    "\n",
    "# questions for retrieval\n",
    "questions = {\n",
    "    \"question\": \"Чем обновлять школы округа?\"\n",
    "}\n",
    "\n",
    "dataset_text = ''.join([char.lower() if not char.isdigit() and char is not None else char for char in questions[\"question\"]])\n",
    "dataset_text = re.sub('  ', ' ', dataset_text) # remove useless space\n",
    "dataset_text = re.sub(r'[\\x00-\\x1F\\x7F-\\x9F]+', '', dataset_text)\n",
    "\n",
    "# questions[\"question\"] = dataset_text\n",
    "dataset_text"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "c009af5a-7aba-46d2-b99d-12310f80f77b",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:43.883038Z",
     "iopub.status.busy": "2024-09-13T08:36:43.882311Z",
     "iopub.status.idle": "2024-09-13T08:36:43.920026Z",
     "shell.execute_reply": "2024-09-13T08:36:43.919187Z",
     "shell.execute_reply.started": "2024-09-13T08:36:43.883009Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "# Вопрос от вашей RAG-системы\n",
    "rag_question = dataset_text\n",
    "\n",
    "# Удаление лишних пробелов\n",
    "df['question'] = df['question'].str.strip()\n",
    "rag_question = rag_question.strip()\n",
    "\n",
    "# Поиск вопроса в базе данных\n",
    "matched_row = df[df['question'] == questions[\"question\"]]\n",
    "\n",
    "# Проверяем, найден ли вопрос\n",
    "if not matched_row.empty:\n",
    "    # Извлекаем правильный ответ и контекст\n",
    "    ground_truth = matched_row['ground_truth'].values[0]\n",
    "    contexts = matched_row['contexts'].values[0]\n",
    "    # Ответ от вашей RAG-системы (замените на реальный ответ)\n",
    "    rag_answer = \"Муниципалитету следует обратиться к законодательству и выяснить, может ли он взять на себя функции регионального оператора в случае его бездействия. Также можно обратиться в соответствующие органы власти для получения рекомендаций и поддержки в данной ситуации.\"\n",
    "\n",
    "    data_samples = {\n",
    "        \"question\": [\n",
    "            dataset_text[:100]\n",
    "        ],\n",
    "        \"answer\": [\n",
    "            rag_answer[:100]\n",
    "        ],\n",
    "        \"contexts\": [\n",
    "            [contexts[:100]]\n",
    "        ],\n",
    "        \"ground_truth\": [\n",
    "            ground_truth[:100]\n",
    "        ],\n",
    "    }\n",
    "\n",
    "    # print(rag_question)\n",
    "    # print(contexts)\n",
    "    # print(ground_truth)\n",
    "    # print(rag_answer)\n",
    "    \n",
    "    # Создаем Dataset для оценки\n",
    "    dataset = Dataset.from_dict(data_samples)\n",
    "\n",
    "else:\n",
    "    print(\"Вопрос не найден в базе данных.\")\n",
    "    \n",
    "# dataset = Dataset.from_pandas(df.iloc[:10])\n",
    "# dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "f01312e2-bd62-439b-83d2-dbfd9e1ea9cb",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:43.922933Z",
     "iopub.status.busy": "2024-09-13T08:36:43.922482Z",
     "iopub.status.idle": "2024-09-13T08:36:43.975301Z",
     "shell.execute_reply": "2024-09-13T08:36:43.974323Z",
     "shell.execute_reply.started": "2024-09-13T08:36:43.922899Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>question</th>\n",
       "      <th>answer</th>\n",
       "      <th>contexts</th>\n",
       "      <th>ground_truth</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>чем обновлять школы округа?</td>\n",
       "      <td>Муниципалитету следует обратиться к законодате...</td>\n",
       "      <td>[|3. |Обновление |Департамент |получение всеми...</td>\n",
       "      <td>Школы округа следует обновлять следующим образ...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                      question  ...                                       ground_truth\n",
       "0  чем обновлять школы округа?  ...  Школы округа следует обновлять следующим образ...\n",
       "\n",
       "[1 rows x 4 columns]"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dataset.to_pandas().head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "872c42bd-e74b-4391-88e1-07bb9658b254",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:43.977791Z",
     "iopub.status.busy": "2024-09-13T08:36:43.976478Z",
     "iopub.status.idle": "2024-09-13T08:36:44.340976Z",
     "shell.execute_reply": "2024-09-13T08:36:44.340065Z",
     "shell.execute_reply.started": "2024-09-13T08:36:43.977758Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                                            contexts  ...                                             answer\n",
      "0  по оснащению образовательного процесса, реализ...  ...  Учебно-наглядные пособия и оборудованные кабин...\n",
      "1  для перевозки обучающихся 0,000 0,000 0,000 3 ...  ...  Учебно-наглядные пособия и оборудованные кабин...\n",
      "\n",
      "[2 rows x 3 columns]\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Путь к файлу Excel\n",
    "input_file = '/home/jupyter/datasphere/s3/hack-object-storage/database/file_for_merge.xlsx'\n",
    "\n",
    "# Чтение файла Excel и создание DataFrame\n",
    "df_2 = pd.read_excel(input_file)\n",
    "\n",
    "# Вывод DataFrame\n",
    "print(df_2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "3146af10-b3ea-4131-a41f-43503d1ce81b",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:36:44.343252Z",
     "iopub.status.busy": "2024-09-13T08:36:44.342151Z",
     "iopub.status.idle": "2024-09-13T08:36:44.375046Z",
     "shell.execute_reply": "2024-09-13T08:36:44.374182Z",
     "shell.execute_reply.started": "2024-09-13T08:36:44.343213Z"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "# Преобразование Dataset в DataFrame\n",
    "dataset_df = dataset.to_pandas()\n",
    "\n",
    "# Объединение df_2 и dataset по колонке 'question'\n",
    "merged_df = pd.merge(dataset_df, df_2[['question', 'answer', 'contexts']], on='question', how='left', suffixes=('', '_new'))\n",
    "\n",
    "# Замена значений колонок answer и contexts\n",
    "merged_df['answer'] = merged_df['answer_new']\n",
    "merged_df['contexts'] = merged_df['contexts_new']\n",
    "\n",
    "# Удаление временных колонок\n",
    "merged_df = merged_df.drop(columns=['answer_new', 'contexts_new'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "41918da9-4809-4a7c-8203-7bd75e11b55c",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:37:05.811359Z",
     "iopub.status.busy": "2024-09-13T08:37:05.810287Z",
     "iopub.status.idle": "2024-09-13T08:37:05.846028Z",
     "shell.execute_reply": "2024-09-13T08:37:05.845229Z",
     "shell.execute_reply.started": "2024-09-13T08:37:05.811315Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[<class 'str'>]\n"
     ]
    }
   ],
   "source": [
    "# Проверка типа данных в колонке 'contexts'\n",
    "types = merged_df['contexts'].apply(type).unique()\n",
    "print(types)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "7bbe11a3-8e71-4b33-b646-fc500bddfc12",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:37:45.297820Z",
     "iopub.status.busy": "2024-09-13T08:37:45.296897Z",
     "iopub.status.idle": "2024-09-13T08:37:45.336357Z",
     "shell.execute_reply": "2024-09-13T08:37:45.335496Z",
     "shell.execute_reply.started": "2024-09-13T08:37:45.297789Z"
    }
   },
   "outputs": [],
   "source": [
    "merged_df['contexts'] = merged_df['contexts'].apply(lambda x: x.split(',') if isinstance(x, str) else [])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "98e24384-9d7e-45b9-9717-d402ede53eb1",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:38:08.452886Z",
     "iopub.status.busy": "2024-09-13T08:38:08.451757Z",
     "iopub.status.idle": "2024-09-13T08:38:08.476039Z",
     "shell.execute_reply": "2024-09-13T08:38:08.475178Z",
     "shell.execute_reply.started": "2024-09-13T08:38:08.452853Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>question</th>\n",
       "      <th>answer</th>\n",
       "      <th>contexts</th>\n",
       "      <th>ground_truth</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>чем обновлять школы округа?</td>\n",
       "      <td>Учебно-наглядные пособия и оборудованные кабин...</td>\n",
       "      <td>[по оснащению образовательного процесса,  реал...</td>\n",
       "      <td>Школы округа следует обновлять следующим образ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>чем обновлять школы округа?</td>\n",
       "      <td>Учебно-наглядные пособия и оборудованные кабин...</td>\n",
       "      <td>[для перевозки обучающихся 0, 000 0, 000 0, 00...</td>\n",
       "      <td>Школы округа следует обновлять следующим образ...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                      question  ...                                       ground_truth\n",
       "0  чем обновлять школы округа?  ...  Школы округа следует обновлять следующим образ...\n",
       "1  чем обновлять школы округа?  ...  Школы округа следует обновлять следующим образ...\n",
       "\n",
       "[2 rows x 4 columns]"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "merged_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "4b01a646-40a5-44ab-a960-9cf172d2c682",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:38:08.478197Z",
     "iopub.status.busy": "2024-09-13T08:38:08.477518Z",
     "iopub.status.idle": "2024-09-13T08:38:08.497624Z",
     "shell.execute_reply": "2024-09-13T08:38:08.496878Z",
     "shell.execute_reply.started": "2024-09-13T08:38:08.478158Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dataset({\n",
      "    features: ['question', 'answer', 'contexts', 'ground_truth', '__index_level_0__'],\n",
      "    num_rows: 2\n",
      "})\n"
     ]
    }
   ],
   "source": [
    "# Преобразование DataFrame в Dataset\n",
    "updated_dataset = Dataset.from_pandas(merged_df)\n",
    "\n",
    "# Вывод информации о Dataset для проверки\n",
    "print(updated_dataset)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "f36a758d-2522-471d-97d3-2064c44ffbb7",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-09-13T08:44:24.163175Z",
     "iopub.status.busy": "2024-09-13T08:44:24.162114Z",
     "iopub.status.idle": "2024-09-13T08:47:22.969035Z",
     "shell.execute_reply": "2024-09-13T08:47:22.968129Z",
     "shell.execute_reply.started": "2024-09-13T08:44:24.163128Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Evaluating: 100%|██████████| 8/8 [02:57<00:00, 22.19s/it]\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=AssertionError('LLM is not set')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_answer_relevance.py\", line 166, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_answer_relevance.py\", line 169, in _ascore\n",
      "    assert self.llm is not None, \"LLM is not set\"\n",
      "AssertionError: LLM is not set\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-8' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=AssertionError('LLM is not set')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_faithfulness.py\", line 256, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_faithfulness.py\", line 262, in _ascore\n",
      "    assert self.llm is not None, \"LLM is not set\"\n",
      "AssertionError: LLM is not set\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-7' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=AssertionError('LLM is not set')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_faithfulness.py\", line 256, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_faithfulness.py\", line 262, in _ascore\n",
      "    assert self.llm is not None, \"LLM is not set\"\n",
      "AssertionError: LLM is not set\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-3' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=<AioRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAUTHENTICATED\n",
      "\tdetails = \"The token has expired 2024-09-13T02:05:54.777233686Z. Now 2024-09-13T08:38:52.863382676Z, which is more than PT10M later\"\n",
      "\tdebug_error_string = \"UNKNOWN:Error received from peer ipv4:158.160.54.160:443 {created_time:\"2024-09-13T08:39:17.415461372+00:00\", grpc_status:16, grpc_message:\"The token has expired 2024-09-13T02:05:54.777233686Z. Now 2024-09-13T08:38:52.863382676Z, which is more than PT10M later\"}\"\n",
      ">>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_recall.py\", line 178, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_recall.py\", line 183, in _ascore\n",
      "    results = await self.llm.generate(\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/llms/base.py\", line 98, in generate\n",
      "    return await agenerate_text_with_retry(\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 189, in async_wrapped\n",
      "    return await copy(fn, *args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 111, in __call__\n",
      "    do = await self.iter(retry_state=retry_state)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 153, in iter\n",
      "    result = await action(retry_state)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/_utils.py\", line 99, in inner\n",
      "    return call(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 418, in exc_check\n",
      "    raise retry_exc.reraise()\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 185, in reraise\n",
      "    raise self.last_attempt.result()\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 114, in __call__\n",
      "    result = await fn(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/llms/base.py\", line 188, in agenerate_text\n",
      "    result = await self.langchain_llm.agenerate_prompt(\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_core/language_models/llms.py\", line 760, in agenerate_prompt\n",
      "    return await self.agenerate(\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_core/language_models/llms.py\", line 1183, in agenerate\n",
      "    output = await self._agenerate_helper(\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_core/language_models/llms.py\", line 1023, in _agenerate_helper\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_core/language_models/llms.py\", line 1007, in _agenerate_helper\n",
      "    await self._agenerate(\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_core/language_models/llms.py\", line 1527, in _agenerate\n",
      "    await self._acall(prompt, stop=stop, run_manager=run_manager, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_community/llms/yandex.py\", line 186, in _acall\n",
      "    text = await acompletion_with_retry(self, prompt=prompt)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_community/llms/yandex.py\", line 345, in acompletion_with_retry\n",
      "    return await _completion_with_retry(**kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 189, in async_wrapped\n",
      "    return await copy(fn, *args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 111, in __call__\n",
      "    do = await self.iter(retry_state=retry_state)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 153, in iter\n",
      "    result = await action(retry_state)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/_utils.py\", line 99, in inner\n",
      "    return call(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 418, in exc_check\n",
      "    raise retry_exc.reraise()\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 185, in reraise\n",
      "    raise self.last_attempt.result()\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 114, in __call__\n",
      "    result = await fn(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_community/llms/yandex.py\", line 343, in _completion_with_retry\n",
      "    return await _amake_request(llm, **_kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_community/llms/yandex.py\", line 294, in _amake_request\n",
      "    operation = await stub.Completion(request, metadata=self.grpc_metadata)  # type: ignore[attr-defined]\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/grpc/aio/_call.py\", line 327, in __await__\n",
      "    raise _create_rpc_error(\n",
      "grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAUTHENTICATED\n",
      "\tdetails = \"The token has expired 2024-09-13T02:05:54.777233686Z. Now 2024-09-13T08:38:52.863382676Z, which is more than PT10M later\"\n",
      "\tdebug_error_string = \"UNKNOWN:Error received from peer ipv4:158.160.54.160:443 {created_time:\"2024-09-13T08:39:17.415461372+00:00\", grpc_status:16, grpc_message:\"The token has expired 2024-09-13T02:05:54.777233686Z. Now 2024-09-13T08:38:52.863382676Z, which is more than PT10M later\"}\"\n",
      ">\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-6' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=AssertionError('LLM is not set')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_precision.py\", line 155, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_precision.py\", line 162, in _ascore\n",
      "    assert self.llm is not None, \"LLM is not set\"\n",
      "AssertionError: LLM is not set\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-5' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=AssertionError('LLM is not set')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_precision.py\", line 155, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_precision.py\", line 162, in _ascore\n",
      "    assert self.llm is not None, \"LLM is not set\"\n",
      "AssertionError: LLM is not set\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-4' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=AssertionError('set LLM before use')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_recall.py\", line 178, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_recall.py\", line 181, in _ascore\n",
      "    assert self.llm is not None, \"set LLM before use\"\n",
      "AssertionError: set LLM before use\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-50' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=AssertionError('LLM is not set')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_answer_relevance.py\", line 166, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_answer_relevance.py\", line 169, in _ascore\n",
      "    assert self.llm is not None, \"LLM is not set\"\n",
      "AssertionError: LLM is not set\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-48' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=<AioRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAUTHENTICATED\n",
      "\tdetails = \"The token has expired 2024-09-13T02:05:54.777233686Z. Now 2024-09-13T08:38:52.863382676Z, which is more than PT10M later\"\n",
      "\tdebug_error_string = \"UNKNOWN:Error received from peer ipv4:158.160.54.160:443 {created_time:\"2024-09-13T08:40:47.695452349+00:00\", grpc_status:16, grpc_message:\"The token has expired 2024-09-13T02:05:54.777233686Z. Now 2024-09-13T08:38:52.863382676Z, which is more than PT10M later\"}\"\n",
      ">>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_faithfulness.py\", line 256, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_faithfulness.py\", line 265, in _ascore\n",
      "    statements = await self.llm.generate(\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/llms/base.py\", line 98, in generate\n",
      "    return await agenerate_text_with_retry(\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 189, in async_wrapped\n",
      "    return await copy(fn, *args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 111, in __call__\n",
      "    do = await self.iter(retry_state=retry_state)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 153, in iter\n",
      "    result = await action(retry_state)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/_utils.py\", line 99, in inner\n",
      "    return call(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 418, in exc_check\n",
      "    raise retry_exc.reraise()\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 185, in reraise\n",
      "    raise self.last_attempt.result()\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 114, in __call__\n",
      "    result = await fn(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/llms/base.py\", line 188, in agenerate_text\n",
      "    result = await self.langchain_llm.agenerate_prompt(\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_core/language_models/llms.py\", line 760, in agenerate_prompt\n",
      "    return await self.agenerate(\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_core/language_models/llms.py\", line 1183, in agenerate\n",
      "    output = await self._agenerate_helper(\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_core/language_models/llms.py\", line 1023, in _agenerate_helper\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_core/language_models/llms.py\", line 1007, in _agenerate_helper\n",
      "    await self._agenerate(\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_core/language_models/llms.py\", line 1527, in _agenerate\n",
      "    await self._acall(prompt, stop=stop, run_manager=run_manager, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_community/llms/yandex.py\", line 186, in _acall\n",
      "    text = await acompletion_with_retry(self, prompt=prompt)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_community/llms/yandex.py\", line 345, in acompletion_with_retry\n",
      "    return await _completion_with_retry(**kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 189, in async_wrapped\n",
      "    return await copy(fn, *args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 111, in __call__\n",
      "    do = await self.iter(retry_state=retry_state)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 153, in iter\n",
      "    result = await action(retry_state)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/_utils.py\", line 99, in inner\n",
      "    return call(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 418, in exc_check\n",
      "    raise retry_exc.reraise()\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/__init__.py\", line 185, in reraise\n",
      "    raise self.last_attempt.result()\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 114, in __call__\n",
      "    result = await fn(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_community/llms/yandex.py\", line 343, in _completion_with_retry\n",
      "    return await _amake_request(llm, **_kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/langchain_community/llms/yandex.py\", line 294, in _amake_request\n",
      "    operation = await stub.Completion(request, metadata=self.grpc_metadata)  # type: ignore[attr-defined]\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/grpc/aio/_call.py\", line 327, in __await__\n",
      "    raise _create_rpc_error(\n",
      "grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAUTHENTICATED\n",
      "\tdetails = \"The token has expired 2024-09-13T02:05:54.777233686Z. Now 2024-09-13T08:38:52.863382676Z, which is more than PT10M later\"\n",
      "\tdebug_error_string = \"UNKNOWN:Error received from peer ipv4:158.160.54.160:443 {created_time:\"2024-09-13T08:40:47.695452349+00:00\", grpc_status:16, grpc_message:\"The token has expired 2024-09-13T02:05:54.777233686Z. Now 2024-09-13T08:38:52.863382676Z, which is more than PT10M later\"}\"\n",
      ">\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-49' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=AssertionError('LLM is not set')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_faithfulness.py\", line 256, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_faithfulness.py\", line 262, in _ascore\n",
      "    assert self.llm is not None, \"LLM is not set\"\n",
      "AssertionError: LLM is not set\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-51' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=AssertionError('LLM is not set')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_answer_relevance.py\", line 166, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_answer_relevance.py\", line 169, in _ascore\n",
      "    assert self.llm is not None, \"LLM is not set\"\n",
      "AssertionError: LLM is not set\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-52' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=AssertionError('set LLM before use')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_recall.py\", line 178, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_recall.py\", line 181, in _ascore\n",
      "    assert self.llm is not None, \"set LLM before use\"\n",
      "AssertionError: set LLM before use\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=AssertionError('set LLM before use')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_recall.py\", line 178, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_recall.py\", line 181, in _ascore\n",
      "    assert self.llm is not None, \"set LLM before use\"\n",
      "AssertionError: set LLM before use\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54' coro=<as_completed.<locals>.sema_coro() done, defined at /home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py:32> exception=AssertionError('LLM is not set')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 34, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 60, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/executor.py\", line 54, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 246, in single_turn_ascore\n",
      "    raise e\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/base.py\", line 239, in single_turn_ascore\n",
      "    score = await asyncio.wait_for(\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/asyncio/futures.py\", line 201, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 232, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_precision.py\", line 155, in _single_turn_ascore\n",
      "    return await self._ascore(row, callbacks)\n",
      "  File \"/home/jupyter/.local/lib/python3.10/site-packages/ragas/metrics/_context_precision.py\", line 162, in _ascore\n",
      "    assert self.llm is not None, \"LLM is not set\"\n",
      "AssertionError: LLM is not set\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>question</th>\n",
       "      <th>contexts</th>\n",
       "      <th>answer</th>\n",
       "      <th>ground_truth</th>\n",
       "      <th>context_precision</th>\n",
       "      <th>faithfulness</th>\n",
       "      <th>answer_relevancy</th>\n",
       "      <th>context_recall</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>чем обновлять школы округа?</td>\n",
       "      <td>[по оснащению образовательного процесса,  реал...</td>\n",
       "      <td>Учебно-наглядные пособия и оборудованные кабин...</td>\n",
       "      <td>Школы округа следует обновлять следующим образ...</td>\n",
       "      <td>0.00000</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>чем обновлять школы округа?</td>\n",
       "      <td>[для перевозки обучающихся 0, 000 0, 000 0, 00...</td>\n",
       "      <td>Учебно-наглядные пособия и оборудованные кабин...</td>\n",
       "      <td>Школы округа следует обновлять следующим образ...</td>\n",
       "      <td>0.22619</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.5</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                      question  ... context_recall\n",
       "0  чем обновлять школы округа?  ...            0.5\n",
       "1  чем обновлять школы округа?  ...            0.5\n",
       "\n",
       "[2 rows x 8 columns]"
      ]
     },
     "execution_count": 35,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from ragas.metrics import (answer_relevancy,faithfulness,context_recall,context_precision)\n",
    "from ragas.metrics.critique import harmfulness\n",
    "from ragas import evaluate\n",
    "from ragas.llms import LangchainLLMWrapper\n",
    "from ragas.embeddings import LangchainEmbeddingsWrapper\n",
    "import ragas\n",
    "\n",
    "evaluation_chat_model = LangchainLLMWrapper(llm)\n",
    "evaluation_embeddings = LangchainEmbeddingsWrapper(embeddings)\n",
    "\n",
    "def evaluate_ragas_dataset(ragas_dataset):\n",
    "    run_config = ragas.RunConfig(timeout=1000, max_retries=1, max_wait=10, max_workers = 1, log_tenacity = True)\n",
    "    result = evaluate(\n",
    "        updated_dataset,  # Run without the last row\n",
    "        metrics=[context_precision,faithfulness,answer_relevancy,context_recall],\n",
    "        llm=llm,\n",
    "        embeddings=embeddings,\n",
    "        raise_exceptions=True,\n",
    "        run_config=run_config,\n",
    "    )\n",
    "    return result.to_pandas()\n",
    "\n",
    "\n",
    "result = evaluate_ragas_dataset(updated_dataset)\n",
    "result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e099243-c93e-4db9-ab61-0010a5f43a92",
   "metadata": {
    "execution": {
     "iopub.status.busy": "2024-09-13T08:36:45.310310Z",
     "iopub.status.idle": "2024-09-13T08:36:45.311070Z",
     "shell.execute_reply": "2024-09-13T08:36:45.310908Z",
     "shell.execute_reply.started": "2024-09-13T08:36:45.310880Z"
    }
   },
   "outputs": [],
   "source": [
    "%pip freeze > requirements.txt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fdd40519-667c-466e-9e80-9feb9490b3c8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "530832ae-ce6b-49ec-b72a-cf1e03509f11",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "be80f3c3-477a-4637-972d-94a06b3e7a04",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8d4e3685-df14-4e6d-b32e-81d28445f325",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9dbd2242-f87d-4eea-ade2-dc127ec9dac2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "DataSphere Kernel",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
